Repository palantir/gradle-revapi, pull requests merged in 2019-10, with the labels that each got.

#46 revapiAcceptAllBreaks succeeds when there are no breaking changes
  changelog/@unreleased/pr-46.v2.yml
  src/main/resources/META-INF/gradle-revapi-accept-breaks.ftl
  src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy
Labels: autorelease, merge when ready

#48 revapiAcceptAllBreaks now works when there are multiple breaks
  build.gradle
  changelog/@unreleased/pr-48.v2.yml
  src/main/java/com/palantir/gradle/revapi/RevapiAcceptAllBreaksTask.java
  src/main/resources/META-INF/gradle-revapi-accept-breaks.ftl
  src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy
  versions.lock
Labels: autorelease, merge when ready

#50 Fix parsing problems when running `revapiAcceptAllBreaks` task
  changelog/@unreleased/pr-50.v2.yml
  src/main/java/com/palantir/gradle/revapi/ConfigManager.java
  src/main/java/com/palantir/gradle/revapi/RevapiAcceptAllBreaksTask.java
  src/main/java/com/palantir/gradle/revapi/config/GradleRevapiConfig.java
  src/main/resources/META-INF/gradle-revapi-accept-breaks.ftl
  src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy
Labels: autorelease, merge when ready

#53 Create .changelog.yml
  .changelog.yml
Labels: merge when ready, no changelog

#42 Exclude scala classes
  changelog/@unreleased/pr-42.v2.yml
  src/main/resources/revapi-configuration.json
  src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy
Labels: autorelease, merge when ready

#66 Ignore magically added groovy methods
  changelog/@unreleased/pr-66.v2.yml
  src/main/resources/revapi-configuration.json
  src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy
Labels: autorelease, merge when ready

#79 Fix interaction with baseline-circleci
  changelog/@unreleased/pr-79.v2.yml
  src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java
  src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy
Labels: autorelease, merge when ready

#82 Fix circleci excavator by not using CIRCLE_TEST_REPORTS
  changelog/@unreleased/pr-82.v2.yml
  src/main/java/com/palantir/gradle/revapi/RevapiReportTask.java
Labels: merge when ready

#88 Change phrasing
  README.md
Labels: no changelog

#85 Adding conjure definition should not fail
  changelog/@unreleased/pr-85.v2.yml
  src/main/java/com/palantir/gradle/revapi/CheckWhitelist.java
  src/main/java/com/palantir/gradle/revapi/ConjureProjectFilters.java
  src/main/java/com/palantir/gradle/revapi/RevapiConfig.java
  src/main/java/com/palantir/gradle/revapi/RevapiJavaTask.java
  src/main/resources/META-INF/gradle-revapi-junit-template.ftl
  src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy
Labels: autorelease, merge when ready
